// AUTO-GENERATED — DO NOT EDIT — re-run scripts/extract-hazbot-sheets.js

import { RuleSet } from "../engine";
import { WildfireDefaults } from "../wildfire/types";

export const ruleSet34: RuleSet<WildfireDefaults> = {
  id: "34",
  categories: [
    {
      id: 1,
      studentAction: "Did not run the simulation",
      feedback: "Hazbot: You haven’t run the model yet. Run it before answering the questions.",
      visualFeedback: "Arrows pointing to the spark tool and the Play button",
      expression: "simulationRuns.length == 0",
    },
    {
      id: 2,
      studentAction: "Ran the simulation but did not change any variables (used default values only)",
      feedback: "Hazbot: Click “Setup” and set the conditions in each zone to experiment with creating a high intensity fire.",
      visualFeedback: "Arrow pointing to the Setup button and Intensity scale",
      expression: "simulationRuns.length > 0 AND NOT setAnyVar",
    },
    {
      id: 3,
      studentAction: "Ran the simulation without changing vegetation",
      feedback: "Hazbot: Try different types of vegetation to see which one produces an intense fire!",
      visualFeedback: "Arrow pointing to spark tool with label: “Red is the most intense fire!”",
      expression: "simulationRuns.length > 0 AND setAnyVar AND NOT setVegetation",
    },
    {
      id: 4,
      studentAction: "Ran and never sees an intense fire.",
      feedback: "Hazbot: Try changing other factors like drought level or wind to make an intense fire!",
      visualFeedback: "Arrow pointing to the Setup button and Intensity scale",
      expression: "simulationRuns.length > 0 AND setVegetation AND NOT sawIntenseFire",
    },
    {
      id: 5,
      studentAction: "Ran the simulation two or more times, changed the vegetation at least once, and saw intense fire.",
      feedback: "Hazbot: Great job! You’re ready to answer the questions below.",
      visualFeedback: "Confetti animation or subtle celebratory visual",
      expression: "simulationRuns.length > 1 AND setVegetation AND sawIntenseFire",
    }
  ],
  factorVariables: [
    {
      name: "simulationRuns",
      definition: "Simulation runs that are initiated by \"SimulationStarted.\"",
      logEvents: ["SimulationStarted", "SimulationStopped", "SImulationRestarted", "SimulationReloaded", "TopBarReloadButtonClicked", "SimulationEnded"],
      details: "Each simulation run is started by 'SimulationStarted', and how it ends is determined by various events listed here.",
    },
    {
      name: "sawIntenseFire",
      definition: "High fire intensity (red) was clearly observed in the simulation outcome.",
      logEvents: ["SimulationEnded->outcome", "SimulationStopped->outcome"],
      details: "Alert: new feature needed.  The 'outcome' field could indicate whether high intensity (red, not orange) appeared significantly in the image generated by the simulation.",
    },
    {
      name: "All other factor variables used above are the same as those used in 33 and are omitted here fore brevity.",
      definition: "",
      logEvents: [],
      details: "",
    }
  ],
  defaults: {},
};
