// Generated by scripts/extract-hazbot-sheets.js (per Req 11). Stub until step 10
// of WM-10 lands the per-tab modules — exporting an empty registry so the bridge
// compiles without rule-set modules. Step 10 replaces this with the real index.
import { RuleSet } from "../engine";
import { WildfireDefaults } from "../wildfire/types";

export const ruleSets: Record<string, RuleSet<WildfireDefaults>> = {};
